closes #1090: merge TypeException and TypingException
informalsystems/apalache pull request #1125
Opened 2021-12-01 08:42 UTC by konnov

closes #1090. Merging `TypeException` and `TypingException`. Many files affected.

- [ ] ~Tests added for any new code~
- [x] Ran `make fmt-fix` (or had formatting run automatically on all files edited)
- [ ] ~Documentation added for any new functionality~
- [x] Entry added to [UNRELEASED.md](./UNRELEASED.md) for any new functionality

2021-12-01 16:44 UTC, shonfeder requested changes
Generally LGT, tho I have some questions about the messaging.

2021-12-01 16:44 UTC, shonfeder commented on tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/config/CheckerExceptionAdapter.scala
> +      FailureMessage("%s: type error: %s".format(findLoc(err.causeExprId), err.getMessage))
Should the message reflect the comment? Perhaps something like:

```suggestion
      FailureMessage("%s: internal error in type checking: %s".format(findLoc(err.causeExprId), err.getMessage))
```

2021-12-01 16:49 UTC, konnov commented on UNRELEASED.md
> +* Merge TypeException and TypingException, see #1090
Right. I was not sure either. But yes, it deserves a note on change in the message format.

2021-12-02 08:36 UTC, konnov commented on UNRELEASED.md
> +* Merge TypeException and TypingException, see #1090
Now it says:

> Change the format of type exceptions, see #1090

2021-12-02 08:37 UTC, konnov commented on tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/config/CheckerExceptionAdapter.scala
> +      NormalErrorMessage("%s: type input error: %s".format(findLoc(err.causeExprId), err.getMessage))
Nice that the tests have caught it. Fixed.

2021-12-02 13:10 UTC, konnov commented
This PR is passing all checks now and ready for your final say :)

2021-12-02 15:03 UTC, shonfeder approved these changes

2021-12-02 16:37 UTC, merged