Support for the option `--features`
informalsystems/apalache pull request #1648
Opened 2022-04-20 09:47 UTC by konnov

Closes #1647. As discussed in #401, this PR introduces the option `--features` that lets us pass experimental features to the tool. The only supported feature in `rows`, which is parsed as `RowsFeature`. When we want to add new features, we have to extend the trait `Feature` with a case class and update the parser in `General`.

For the moment, I am not adding any documentation to the user manual. I will extend the manual section on types, when we start the transition period to Type System 1.2.

- [x] Tests added for any new code
- [x] Ran `make fmt-fix` (or had formatting run automatically on all files edited)
- [ ] Documentation added for any new functionality
- [ ] Entry added to [UNRELEASED.md](./UNRELEASED.md) for any new functionality

2022-04-20 10:02 UTC, thpani reviewed
Code LGTM, but I think we should discuss how this will evolve once the feature becomes stable. Do you have a plan for that?

2022-04-21 07:04 UTC, thpani commented on mod-tool/src/main/scala/at/forsyte/apalache/tla/tooling/opt/General.scala
> +        | - rows: enable row typing as explained in ADR-014
Resolving because we discussed this offline

2022-04-21 07:06 UTC, thpani approved these changes
LGTM (modulo fixing the output on that failing integration test)

2022-04-22 14:20 UTC, shonfeder requested changes
Leaving a note that I have requested a change set via #1652

2022-04-26 08:21 UTC, thpani commented
> Leaving a note that I have requested a change set via #1652

@shonfeder quick workflow question: I think we don't necessarily need to block on this?
It should be fine to review #1652 against this branch, then rebase it on `unstable` once this PR gets merged?

2022-04-26 13:00 UTC, shonfeder approved these changes

2022-04-26 13:33 UTC, merged