Disabled caching
informalsystems/apalache pull request #276
Opened 2020-10-13 16:31 UTC by Kukovec

After some discussion, we've found caching to be unnecessary, so it has been disabled. Closes #273.

2020-10-13 17:52 UTC, shonfeder requested changes
I think a line was missed, and I have some reservations about leaving the commented out code in place. I suggest that we either remove all the caching stuff (including the tests in https://github.com/informalsystems/apalache/tree/unstable/tla-pp/src/test/scala/at/forsyte/apalache/tla/pp/TestCaching.scala and the `Cacher` module in https://github.com/informalsystems/apalache/tree/unstable/tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/Cacher.scala) or we should leave the cacher usage in place here, and just disable it with a feature flag. Otherwise, we end up with dead code (both commented out and unused) and that could just end up as clutter down the line.

2020-10-13 17:52 UTC, shonfeder commented on tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/passes/UnrollPassImpl.scala
>      val cacher = Cacher( nameGenerator, tracker )
Shouldn't this also be removed, along with the import?

2020-10-13 18:03 UTC, Kukovec commented
> 
> 
> I think a line was missed, and I have some reservations about leaving the commented out code in place. I suggest that we either remove all the caching stuff (including the tests in https://github.com/informalsystems/apalache/tree/unstable/tla-pp/src/test/scala/at/forsyte/apalache/tla/pp/TestCaching.scala and the `Cacher` module in https://github.com/informalsystems/apalache/tree/unstable/tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/Cacher.scala) or we should leave the cacher usage in place here, and just disable it with a feature flag. Otherwise, we end up with dead code (both commented out and unused) and that could just end up as clutter down the line.

Cacher will eventually be reworked and reintroduced to facilitate operator annotations, so the other classes should stay for now. This was more of a hotfix to resolve #273, which I was told was urgent.

2020-10-13 18:06 UTC, shonfeder commented
If it's too urgent to bear the time needed for a feature flag here, then I'd advocate for at least adding a comment above the affected code with a `TODO` noting the problem, in conjunction with an open issue that tracks it.

2020-10-13 21:09 UTC, konnov approved these changes
Let's merge it, so it does not block MBT. But in the future, we should improve the code and add more integration tests.

2020-10-14 01:05 UTC, shonfeder commented
I wouldn't block the merge, but it should take literally 2 minutes to add a comment explaining what's going on here.

2020-10-14 01:14 UTC, shonfeder approved these changes
Added some suggestions with the comment I've requested.

Feel free to ignore/correct if they are off base or wrong, but I figure making them available for a quick apply shouldn't reduce overhead. :)

2020-10-14 01:14 UTC, shonfeder commented on tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/passes/UnrollPassImpl.scala
> +//    val cached = cacher( module )
```suggestion
//    cacher is currently causing recursive operators to break (see #276 for context)
//    val cached = cacher( module )
```

2020-10-14 01:14 UTC, shonfeder commented on tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/passes/UnrollPassImpl.scala
>      val cacher = Cacher( nameGenerator, tracker )
```suggestion
 //  TODO: re-enable cacher once caching is reworked (see #276 for context)
 //  cacher is currently causing recursive operators to break
 //  val cacher = Cacher( nameGenerator, tracker )
```

2020-10-14 10:48 UTC, Kukovec commented
I've cleared the unused code and added a TODO for the future.

2020-10-14 11:06 UTC, merged