Manual top-level operators
informalsystems/apalache pull request #419
Opened 2021-01-11 13:18 UTC by konnov

I have started to write Part 2 of the language manual. To avoid huge PRs this time, this PR contains material on the overview of user-defined operators and details on top-level user-defined operators. The other pages are just stubs.

- [X] Entry added to [CHANGES.md](./CHANGES.md) for any new functionality

Pages in readable form can be found here:
 - [User operators](https://github.com/informalsystems/apalache/blob/igor/lang2/docs/src/lang/user-operators.md)
 - [Top-level operators](https://github.com/informalsystems/apalache/blob/igor/lang2/docs/src/lang/top-level-operators.md)

2021-01-13 14:40 UTC, shonfeder requested changes
Lol. Forgot to hit submit on these comments last week! Sorry :/

2021-01-13 17:02 UTC, konnov commented on docs/src/lang/lambdas.md
> +[[Back to user operators]](./user-operators.md)
They are all related to user operators. Good idea.

2021-01-13 17:05 UTC, konnov commented on docs/src/lang/user-operators.md
> +## For the impatient
I am trying to achieve two things at once here: Give the reference material to those who know the language already, and give an introduction to the concepts to those who don't know it yet. So "the impatient" section is for those who want to refresh their memory without reading too much introductory text.

2021-01-13 17:35 UTC, konnov commented on docs/src/lang/lambdas.md
> +[[Back to user operators]](./user-operators.md)
Fixed

2021-01-13 17:52 UTC, konnov commented on docs/src/lang/user-operators.md
> +whole system computation! The operator `Next` describes a single step of the
Fixed

2021-01-13 17:52 UTC, konnov commented on docs/src/lang/user-operators.md
> + - [Top-level operator definitions](./top-level-operators.md)
Fixed

2021-01-13 17:55 UTC, shonfeder commented on docs/src/lang/user-operators.md
> +## For the impatient
I'd content that, with the table of contents now available in the side bar, you don't need this redundant listings We know have the same items listed out in triplicate. Those who just need quick reference will have it at their fingertips in the sidebar nav.

2021-01-13 17:56 UTC, konnov commented on docs/src/lang/user-operators.md
> +## For the impatient
That makes sense. I will remove that section

2021-01-13 17:58 UTC, konnov commented on docs/src/lang/top-level-operators.md
> +A(p_1, ..., p_n) == body_of_A
Right. I have renamed the parameters of `B` to `p_1, ..., p_k`, to make it more obvious.

2021-01-14 14:34 UTC, shonfeder approved these changes
LGTM

2021-01-14 18:14 UTC, merged